docs: Refactor create-notebook page for GPU link
canonical/data-science-stack pull request #132
Opened 2024-05-29 12:51 UTC by kimwnasptd

This PR revamps the page for creating notebooks by:
1. Adding sections for the different steps, instead of having lists
2. Adding a `Next Steps` section, to redirect users to relevant content

This PR should be merged after https://github.com/canonical/data-science-stack/pull/131, which adds a `ref` link to the NVIDIA GPU page.

cc @afgambin

2024-05-29 12:59 UTC, kimwnasptd commented
The build step here is failing since I'm referencing the page, whose change is added in https://github.com/canonical/data-science-stack/pull/131

```
/home/docs/checkouts/readthedocs.org/user_builds/canonical-data-science-stack/checkouts/132/docs/how-to/jupyter-notebook/create-notebook.rst:64: WARNING: undefined label: 'nvidia-gpu'
```

2024-05-30 14:21 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
> +To see a list of recommended images and their aliases, see:
```suggestion
To see a list of recommended images and their aliases, run:
```

2024-05-30 14:24 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
> +Before creating a notebook, you need to select an image that includes the packages and toolkits you need.
```suggestion
To create a notebook, you need to select an image that includes the packages and toolkits you need.
```

2024-05-30 14:26 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
> +The help text includes a list of recommended images and aliases so you don't need to type the full image name.
```suggestion

```

2024-05-30 14:26 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
> +For this guide, we will use the image `kubeflownotebookswg/jupyter-scipy:v1.8.0`
```suggestion
For this guide, the image `kubeflownotebookswg/jupyter-scipy:v1.8.0` is used.
```

2024-05-30 14:27 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
> +Create a new notebook using ``dss create``:
```suggestion
You can create and launch a new notebook using ``dss create``:
```

2024-05-30 14:28 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
> +This will pull the notebook image and start a Notebook server, printing the URL of the notebook once complete.  Expected output:
```suggestion
This command pulls the notebook image and start a Notebook server, printing the URL of the notebook once complete.  You should expect this output:
```

2024-05-30 14:30 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
> +To :doc:`access the Notebook </how-to/jupyter-notebook/access-ui>`, use the URL provided in the output.
```suggestion
To :doc:`access the notebook </how-to/jupyter-notebook/access-ui>`, use the URL provided in the launching phase.
```

2024-05-30 14:31 UTC, afgambin commented on docs/how-to/jupyter-notebook/create-notebook.rst
>  Conclusion
I am not sure these conclusions sections are actually needed for how-to guides. I will add this to the backlog list.

2024-05-30 14:34 UTC, afgambin requested changes
@kimwnasptd first round of reviews completed!

2024-06-14 07:18 UTC, afgambin commented
@kimwnasptd I think this PR is no longer needed. It can be closed and brand deleted.

2024-08-01 10:04 UTC, closed without merging