feat: add dss snap
canonical/data-science-stack pull request #42
Opened 2024-03-05 07:53 UTC by DnPlas

TODO

2024-03-12 13:07 UTC, kenvandine requested changes

2024-03-12 13:07 UTC, kenvandine commented on snap/snapcraft.yaml
> +plugs:
style nit, I prefer to put global plug declarations above parts.  The parts declarations can get long in some snaps which makes it hard to notice something like the global plugs.

2024-03-12 13:07 UTC, kenvandine commented on snap/snapcraft.yaml
> +apps:
style nit, just like the plugs I prefer defining the apps section above parts for the same reason.

2024-03-12 13:07 UTC, kenvandine commented on snap/snapcraft.yaml
> +      - dot-dss-config
Including dot-dss-config here is redundant

2024-03-12 13:07 UTC, kenvandine commented on snap/snapcraft.yaml
> +      craftctl set version="0.1"
An easy way to avoid needing to do this would be to create an initial tag like "0.0" as a pre-release.  Not important though.

2024-03-12 17:05 UTC, kenvandine approved these changes
Thanks, this looks great now

2024-03-14 15:20 UTC, orfeas-k commented on snapcraft.yaml
> +summary: a ML development and experimentation environment manager
```suggestion
summary: an ML development and experimentation environment manager
```
nit :face_with_spiral_eyes:

2024-03-14 15:20 UTC, orfeas-k commented on snapcraft.yaml
> +     The DSS is a tool that allows users of workstations to deploy
```suggestion
     The DSS is a tool that allows workstations users to deploy
```
?

2024-03-14 15:20 UTC, orfeas-k commented on snapcraft.yaml
> +     The DSS is a tool that allows users of workstations to deploy
not really sure about it, if you don't think it's needed, you can keep it as is.

2024-03-15 08:49 UTC, orfeas-k approved these changes
Thank you @DnPlas :smile:

2024-03-15 08:53 UTC, merged