Create PoC scripts for emulating an NVIDIA and Intel setup
canonical/data-science-stack pull request #60
Opened 2024-03-31 21:19 UTC by kimwnasptd

Some PoC scripts for how the DSS will look like on different GPU vendors

2024-04-02 06:46 UTC, misohu reviewed
I have tested the intel gpu plugin version on my local PC .... the script reports successful deployment of plugin and everything except it gets stuck on notebook deployment. The daemon set will not scale up. 

```
❯ kubectl get daemonset  --all-namespaces
NAMESPACE                NAME               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                        AGE
default                  intel-gpu-plugin   0         0         0       0            0           intel.feature.node.kubernetes.io/gpu=true,kubernetes.io/arch=amd64   10m
```

I did just small debugging. From the line above you can see Node Selector section refers to labels which I could not find on top of my node. My note is here 

```
❯ kubectl get nodes hyrule -o yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    nfd.node.kubernetes.io/master.version: v0.14.1
    nfd.node.kubernetes.io/worker.version: v0.14.1
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 10.241.64.1/24
    projectcalico.org/IPv4VXLANTunnelAddr: 10.1.137.0
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-04-02T06:29:02Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: hyrule
    kubernetes.io/os: linux
    microk8s.io/cluster: "true"
    node.kubernetes.io/microk8s-controlplane: microk8s-controlplane
  name: hyrule
  resourceVersion: "2323"
  uid: 72c30402-8f54-4aa5-88cc-6aff98834e7f
spec: {}
status:
  addresses:
  - address: 192.168.100.34
    type: InternalIP
  - address: hyrule
    type: Hostname
  allocatable:
    cpu: "20"
    ephemeral-storage: 234954632Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32487996Ki
    pods: "110"
  capacity:
    cpu: "20"
    ephemeral-storage: 236003208Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32590396Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2024-04-02T06:29:27Z"
    lastTransitionTime: "2024-04-02T06:29:27Z"
    message: Calico is running on this node
    reason: CalicoIsUp
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2024-04-02T06:41:29Z"
    lastTransitionTime: "2024-04-02T06:29:02Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2024-04-02T06:41:29Z"
    lastTransitionTime: "2024-04-02T06:29:02Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2024-04-02T06:41:29Z"
    lastTransitionTime: "2024-04-02T06:29:02Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2024-04-02T06:41:29Z"
    lastTransitionTime: "2024-04-02T06:29:21Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - docker.io/ubuntu/mlflow@sha256:2148a9775662dba819226fc543eeeab8c197de1ddc7e6b7c529c3c743c1d7f06
    - docker.io/ubuntu/mlflow:2.1.1_1.0-22.04
    sizeBytes: 307311749
  - names:
    - docker.io/calico/cni@sha256:9a2c99f0314053aa11e971bd5d72e17951767bf5c6ff1fd9c38c4582d7cb8a0a
    - docker.io/calico/cni:v3.25.1
    sizeBytes: 89884044
  - names:
    - docker.io/calico/node@sha256:0cd00e83d06b3af8cd712ad2c310be07b240235ad7ca1397e04eb14d20dcc20f
    - docker.io/calico/node:v3.25.1
    sizeBytes: 88335791
  - names:
    - registry.k8s.io/nfd/node-feature-discovery@sha256:a5e9f35119a1df99fba159002487e3b85fe439a43f166eb43fe67e1b99a19531
    - registry.k8s.io/nfd/node-feature-discovery:v0.14.1
    sizeBytes: 72443068
  - names:
    - docker.io/calico/kube-controllers@sha256:02c1232ee4b8c5a145c401ac1adb34a63ee7fc46b70b6ad0a4e068a774f25f8a
    - docker.io/calico/kube-controllers:v3.25.1
    sizeBytes: 31908610
  - names:
    - docker.io/coredns/coredns@sha256:a0ead06651cf580044aeb0a0feba63591858fb2e43ade8c9dea45a6a89ae7e5e
    - docker.io/coredns/coredns:1.10.1
    sizeBytes: 16190758
  - names:
    - docker.io/cdkbot/hostpath-provisioner@sha256:ac51e50e32b70e47077fe90928a7fe4d3fc8dd49192db4932c2643c49729c2eb
    - docker.io/cdkbot/hostpath-provisioner:1.5.0
    sizeBytes: 11717290
  - names:
    - docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    - docker.io/library/busybox:1.28.4
    sizeBytes: 727869
  - names:
    - registry.k8s.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
    - registry.k8s.io/pause:3.7
    sizeBytes: 311278
  nodeInfo:
    architecture: amd64
    bootID: 23fa6324-1594-4872-8bf8-e624e1e63911
    containerRuntimeVersion: containerd://1.6.28
    kernelVersion: 6.5.0-26-generic
    kubeProxyVersion: v1.29.2
    kubeletVersion: v1.29.2
    machineID: 4c9cbb69c2404999949fbd0e5cc5c006
    operatingSystem: linux
    osImage: Ubuntu 22.04.4 LTS
    systemUUID: 619dcb74-31dd-7378-7d9e-50ebf6992dee
 ```
 
 Was this working on your side @kimwnasptd ?

2024-04-02 06:46 UTC, misohu commented on poc/README.md
> +
We can mention that you need sudo privileges to run the script.

2024-04-02 06:46 UTC, misohu commented on poc/intel/manifests/mlflow.yaml
> +  labels:
Missing common label across all dss components. Maybe: 
```
app.kubernetes.io/part-of: dss
```

2024-04-02 06:46 UTC, misohu commented on poc/intel/manifests/mlflow.yaml
> +  labels:
If we decide to go for the label we should add it to every object.

2024-04-02 06:46 UTC, misohu commented on poc/intel/manifests/notebooks.yaml
> +      storage: 10Gi
I think we should add 
```
storageClassName: microk8s-hostpath
volumeMode: Filesystem
```

Its used by default in this microk8s setup but for sake of clarity I would add it.

2024-04-02 06:46 UTC, misohu commented on poc/nvidia/cleanup.sh
> +#!/bin/bash
This will completely remove microk8s from pc. We can add small warning in README maybe user was using the microk8s for somthing else not just dss.

2024-04-02 06:46 UTC, misohu commented on poc/nvidia/cleanup.sh
> +sudo snap remove microk8s --purge
Maybe we can add message that dss was successfully removed.

2024-04-02 06:46 UTC, misohu commented on poc/nvidia/manifests/mlflow.yaml
Why don't we have  `common-manifests` folder ? Now we are repeating same manifests for intel and nvidia. This might lead to simple mistakes while refactoring in the future.

2024-04-02 06:46 UTC, misohu commented on poc/intel/deploy.sh
> +sudo microk8s enable rbac
just wondering if this is needed ?

2024-04-03 07:58 UTC, kimwnasptd commented on poc/README.md
> +
done

2024-04-03 08:11 UTC, kimwnasptd commented on poc/intel/manifests/notebooks.yaml
> +      storage: 10Gi
done

2024-04-03 08:51 UTC, kimwnasptd commented on poc/nvidia/cleanup.sh
> +#!/bin/bash
Good point! Pushed a commit

2024-04-03 08:53 UTC, kimwnasptd commented on poc/intel/deploy.sh
> +sudo microk8s enable rbac
not really for a PoC, but thought it would be what people would expect if they got a K8s cluster so left it there for that reason

2024-04-03 09:15 UTC, hector-cao requested changes
Some minor comments from quick walk through the PR

2024-04-03 11:35 UTC, kimwnasptd commented on poc/README.md
> +NOTE: You will need `sude` previleges to be able to run this script
Ugh, indeed. Changing now

2024-04-03 13:42 UTC, kimwnasptd commented on poc/nvidia/cleanup.sh
> +sudo snap remove microk8s --purge
pushed a commit

2024-04-03 15:05 UTC, kimwnasptd commented on poc/nvidia/manifests/mlflow.yaml
Pushed a commit for this that 
1. Creates a `poc/common-manifests` folder
2. Put all the common yamls for MLFlow, PVC and namespace to that folder
3. Only keep the different notebooks per intel/nvidia
4. Update `deploy.sh` scripts to use the `poc/common-manifests` folder

2024-04-03 15:09 UTC, kimwnasptd commented on poc/nvidia/nvidia-drivers.sh
> +  sudo nvidia-smi
We don't, I had only played with it in the past but looks like we can omit it. Pushed a commit to remove sudo here

2024-04-03 15:09 UTC, kimwnasptd commented on poc/README.md
> +NOTE: You will need `sude` previleges to be able to run this script
Pushed a commit for this

2024-04-03 15:14 UTC, kimwnasptd commented
@misohu I'm not sure why it failed on you. I tried this with an internal lab machine that had a dedicated Intel GPU and saw a notebook getting scheduled. I'd suggest we get this in for now though and then get feedback from the Intel team on running this with integrated GPUs.

2024-04-03 15:15 UTC, kimwnasptd commented
@misohu @hector-cao I did a pass and addressed your comments. PTAL and if you are OK let me know.

I'll be looking in parallel on why the linting tests failed

2024-04-03 15:53 UTC, hector-cao commented
> @misohu @hector-cao I did a pass and addressed your comments. PTAL and if you are OK let me know.
> 
> I'll be looking in parallel on why the linting tests failed

That is ok for me, i will let other folks to officially approve the PR

2024-04-04 07:43 UTC, misohu approved these changes
Approving @kimwnasptd just please keep in mind I was not able to make it run on my local laptop nor on the aws instance.

2024-04-04 08:35 UTC, merged